version: '3.8'

services:
  # Nginx 反向代理服务
  nginx:
    image: nginx:alpine
    container_name: bambumoon_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/ssl
      - ../dist:/var/www/bambumoon-sites/main-site/dist
      - /Users/macmima1234/Downloads/company:/var/www/bambumoon-sites/company
    restart: unless-stopped
    depends_on:
      - certbot
    networks:
      - bambumoon_network

  # SSL 证书管理
  certbot:
    image: certbot/certbot
    container_name: bambumoon_certbot
    volumes:
      - ./ssl:/etc/letsencrypt
      - ./ssl-challenges:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --email admin@bambumoon.cn --agree-tos --no-eff-email -d bambumoon.cn -d www.bambumoon.cn -d company.bambumoon.cn
    networks:
      - bambumoon_network

  # 网站监控
  monitoring:
    image: prom/prometheus:latest
    container_name: bambumoon_monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    restart: unless-stopped
    networks:
      - bambumoon_network

  # 日志分析
  logrotate:
    image: alpine:latest
    container_name: bambumoon_logrotate
    volumes:
      - /var/log:/var/log
    command: |
      sh -c "
        echo '0 2 * * * /usr/sbin/logrotate /etc/logrotate.conf' | crontab -
        crond -f
      "
    restart: unless-stopped

networks:
  bambumoon_network:
    driver: bridge

volumes:
  ssl_data:
  prometheus_data: